Handle paths used by distribution packages
Update the script to use the paths used by the distribution package
`musl-dev', which put includes in `/usr/include/x86_64-linux-musl' and
libraries in `/usr/lib/x86_64-linux-musl'.

diff --git a/musl-clang b/musl-clang
--- a/musl-clang
+++ b/musl-clang
@@ -8,10 +8,21 @@
 # See LICENSE file for copyright and license details.
 #
 
-PREFIX=${MUSL_PREFIX:-"/usr/local/musl"}
-if [ ! -d "${PREFIX}" ]; then
-	echo "invalid prefix: ${PREFIX}"
-	return 1
+set -e
+set -u
+
+arch=$(uname -m)
+
+incdir="/usr/include/$arch-linux-musl"
+if [ ! -d "$incdir" ]; then
+	echo "invalid include directory: $incdir" >/dev/stderr
+	exit 1
+fi
+
+libdir="/usr/lib/$arch-linux-musl"
+if [ ! -d "$libdir" ]; then
+	echo "invalid lib directory: $libdir" >/dev/stderr
+	exit 1
 fi
 
 CPP=no
@@ -30,7 +41,7 @@ hasNo() {
 	shift 1
 
 	for e in "$@"; do
-		if [ "$e" = "${pat}" ]; then
+		if [ "$e" = "$pat" ]; then
 			return 1
 		fi
 	done
@@ -41,7 +52,7 @@ ARGS="-nostdinc"
 TAIL=""
 
 if hasNo '-nostdinc' "$@"; then
-	ARGS="${ARGS} -isystem ${PREFIX}/include"
+	ARGS="$ARGS -isystem $incdir"
 fi
 
 if \
@@ -49,35 +60,31 @@ if \
 	hasNo '-S' "$@" && \
 	hasNo '-E' "$@"
 then
-	ARGS="${ARGS} -nostdlib"
-	ARGS="${ARGS} -Wl,-dynamic-linker=${PREFIX}/lib/libc.so"
-	ARGS="${ARGS} -L${PREFIX}/lib"
-	#ARGS="${ARGS} -Wl,-rpath=${PREFIX}/lib"
+	ARGS="$ARGS -nostdlib"
+	ARGS="$ARGS -Wl,-dynamic-linker=$libdir/libc.so"
+	ARGS="$ARGS -L$libdir"
 
 	if hasNo '-nostartfiles' "$@" && \
 	   hasNo '-nostdlib' "$@" && \
 	   hasNo '-nodefaultlibs' "$@"
 	then
-		ARGS="${ARGS} ${PREFIX}/lib/crt1.o"
-		ARGS="${ARGS} ${PREFIX}/lib/crti.o"
+		ARGS="$ARGS $libdir/crt1.o"
+		ARGS="$ARGS $libdir/crti.o"
 
-		TAIL="${TAIL} ${PREFIX}/lib/crtn.o"
+		TAIL="$TAIL $libdir/crtn.o"
 	fi
 
 	if hasNo '-nostdlib' "$@" && \
 	   hasNo '-nodefaultlibs' "$@"
 	then
-		if [ "${CPP}" = "yes" ]; then
-			TAIL="${TAIL} -lc++"
-			TAIL="${TAIL} -lunwind"
-			TAIL="${TAIL} -lm"
+		if [ "$CPP" = "yes" ]; then
+			TAIL="$TAIL -lc++"
+			TAIL="$TAIL -lunwind"
+			TAIL="$TAIL -lm"
 		fi
-		TAIL="${TAIL} -lc"
-		#TAIL="${TAIL} -Wl,-Bstatic -lcompiler_rt"
+		TAIL="$TAIL -lc"
 	fi
 fi
 
-#echo "# $0" "$@" >&2
-#set -x
-exec ${CLANG} ${ARGS} "$@" ${TAIL}
+exec "$CLANG" $ARGS "$@" $TAIL
 
